# -*- mode: ruby -*-
# vi: set ft=ruby :


machines = {
  "node01" => {"memory" => "640", "cpu" => "1", "ip" => "101", "image" => "bento/ubuntu-22.04"},
  "node04" => {"memory" => "640", "cpu" => "1", "ip" => "104", "image" => "bento/ubuntu-22.04"}
}

Vagrant.configure("2") do |config|

  machines.each do |name, conf|

    config.vm.define "#{name}" do |machine|

      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}"
      machine.vm.network "private_network", ip: "10.10.10.#{conf["ip"]}"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "vm_#{name}"
        vb.memory = "#{conf["memory"]}"
        vb.cpus = "#{conf["cpu"]}"
      end
      machine.vm.provision "shell", path: "docker.sh"

      if "#{name}" == "node01"
        machine.vm.provision "shell", path: "main.sh"
      else
        machine.vm.provision "shell", path: "worker.sh"
      end
    end
  end
end